In [25]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)

In [26]:
#df = pd.read_csv('data/atx_crash_data_2018-2026.csv')
df = pd.read_csv(r'C:\Users\emily.wilkins\Documents\Project Nova BI to AI\Austin_Crash_Report_Data_-_Crash_Level_Records.csv')

C:\Users\emily.wilkins\AppData\Local\Temp\ipykernel_16336\1275001710.py:2: DtypeWarning: Columns (4,8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r'C:\Users\emily.wilkins\Documents\Project Nova BI to AI\Austin_Crash_Report_Data_-_Crash_Level_Records.csv')

In [27]:
df.head()

,ID,Crash ID,crash_fatal_fl,case_id,rpt_block_num,rpt_street_name,rpt_street_sfx,crash_speed_limit,road_constr_zone_fl,latitude,longitude,crash_sev_id,sus_serious_injry_cnt,nonincap_injry_cnt,poss_injry_cnt,non_injry_cnt,unkn_injry_cnt,tot_injry_cnt,death_cnt,units_involved,point,motor_vehicle_death_count,motor_vehicle_serious_injury_count,bicycle_death_count,bicycle_serious_injury_count,pedestrian_death_count,pedestrian_serious_injury_count,motorcycle_death_count,motorcycle_serious_injury_count,other_death_count,other_serious_injury_count,onsys_fl,private_dr_fl,micromobility_serious_injury_count,micromobility_death_count,Crash timestamp (US/Central),Crash timestamp,Is deleted,Is temporary record,Law enforcement fatality count,Reported street prefix,Estimated Maximum Comprehensive Cost,Estimated Total Comprehensive Cost,Location ID,Location group,Address
0,594,13647768.0,False,140101040,800,NOT REPORTED,LN,-1.0,False,NaN,NaN,5,0,0,0,4,0,0,0,Large passenger vehicle,NaN,0,0,0,0,0,0,0,0,0,0,True,False,0,0,01/10/2014 02:25:00 PM,01/10/2014 08:25:00 PM,False,False,0,NaN,20000,80000,NaN,NaN,800 US 183 SVRD
1,697,13650667.0,False,140080110,12700,NOT REPORTED,HWY,50.0,False,NaN,NaN,5,0,0,0,1,0,0,0,Passenger car,NaN,0,0,0,0,0,0,0,0,0,0,True,False,0,0,01/08/2014 02:12:00 AM,01/08/2014 08:12:00 AM,False,False,0,NaN,20000,20000,NaN,NaN,12700 US 183 SVRD
2,2359,13688477.0,False,140440934,NaN,NOT REPORTED,NaN,45.0,False,NaN,NaN,5,0,0,0,2,0,0,0,Passenger car,NaN,0,0,0,0,0,0,0,0,0,0,True,False,0,0,02/13/2014 01:11:00 PM,02/13/2014 07:11:00 PM,False,False,0,NaN,20000,40000,NaN,NaN,LOOP 1 SVRD & PARK BEND DR
3,2232,13687795.0,False,140310942,5401,NOT REPORTED,HWY,-1.0,False,NaN,NaN,0,0,0,0,1,1,0,0,Large passenger vehicle & Passenger car,NaN,0,0,0,0,0,0,0,0,0,0,True,False,0,0,01/31/2014 11:00:00 AM,01/31/2014 05:00:00 PM,False,False,0,NaN,20000,40000,NaN,NaN,5401 IH 35
4,2706,13699891.0,False,140510958,8900,NOT REPORTED,BLVD,45.0,False,NaN,NaN,5,0,0,0,2,0,0,0,Motor vehicle – other & Passenger car,NaN,0,0,0,0,0,0,0,0,0,0,True,False,0,0,02/20/2014 03:07:00 PM,02/20/2014 09:07:00 PM,False,False,0,NaN,20000,40000,NaN,NaN,8900 US 183 SVRD

In [28]:
#Filter data to only include data from 2018-2026
df['Crash timestamp (US/Central)'] = pd.to_datetime(df['Crash timestamp (US/Central)'])
print(df['Crash timestamp (US/Central)'].dtype)

C:\Users\emily.wilkins\AppData\Local\Temp\ipykernel_16336\2399727563.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Crash timestamp (US/Central)'] = pd.to_datetime(df['Crash timestamp (US/Central)'])

datetime64[ns]

In [29]:
df['year'] = df['Crash timestamp (US/Central)'].dt.year

In [30]:
desired_years= [2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026]
df = df[df['year'].isin(desired_years)]

In [31]:
#Filter data to only include needed columns
df = df.loc[:, [
'ID'
,'Crash ID'
,'crash_fatal_fl'
,'case_id'
,'rpt_block_num'
,'rpt_street_name'
,'rpt_street_sfx'
,'crash_speed_limit'
,'road_constr_zone_fl'
,'latitude'
,'longitude'
,'crash_sev_id'
,'death_cnt'
,'units_involved'
,'point'
,'onsys_fl'
,'private_dr_fl'
,'Crash timestamp (US/Central)'
,'Estimated Total Comprehensive Cost'
,'Location group'
,'Address'
]]

In [32]:
df.head()

,ID,Crash ID,crash_fatal_fl,case_id,rpt_block_num,rpt_street_name,rpt_street_sfx,crash_speed_limit,road_constr_zone_fl,latitude,longitude,crash_sev_id,death_cnt,units_involved,point,onsys_fl,private_dr_fl,Crash timestamp (US/Central),Estimated Total Comprehensive Cost,Location group,Address
44014,92807,16839445.0,False,190080930,1200,MOPAC,EXPY,65.0,False,30.288379,-97.762235,5,0,Large passenger vehicle & Passenger car,POINT (-97.76223487 30.28837926),True,False,2019-01-09 14:12:00,20000,2.0,1200 N LOOP 1
44015,93467,16854755.0,False,190151441,1700,OHLEN,RD,35.0,False,30.363175,-97.717782,5,0,Passenger car,POINT (-97.71778247 30.36317476),True,False,2019-01-15 20:58:00,40000,1.0,W OHLEN RD & N US 183 SVRD
44018,93480,16854819.0,False,190160293,3100,IH 35,HWY,60.0,False,30.234100,-97.740976,5,0,Large passenger vehicle,POINT (-97.7409757 30.23410002),True,False,2019-01-16 07:28:00,40000,2.0,3100 S IH 35
44021,94289,16870096.0,False,190260764,300,E PARMER,LN,50.0,False,30.405288,-97.663709,3,0,Large passenger vehicle,POINT (-97.6637086677118 30.405287627981),False,False,2019-01-26 13:41:00,460000,1.0,E PARMER LN & MC CALLEN PASS
44022,93948,16863200.0,False,190230902,8900,GALEWOOD,DR,25.0,False,30.366156,-97.715854,2,0,Large passenger vehicle & Passenger car,POINT (-97.71585363 30.3661555),False,False,2019-01-23 13:25:00,540000,1.0,8900 GALEWOOD DR

In [33]:
#Extract units from units involved column to create unit flags
def extract_units(s):
    a_list = []
    for units in s.split('&'):
        for unit in units.split('â€“'):
            a_list.append(unit.strip())

    return a_list

unit_cats = list(set(i for s in df['units_involved'].str.lower().map(extract_units).to_list() for i in s))
unit_cats.remove('other/unknown') # combine with "other"
unit_cats

['micromobility device',
 'train',
 'e-scooter',
 'pedestrian',
 'motorcycle',
 'large passenger vehicle',
 'bicycle',
 'passenger car',
 'motor vehicle – other']

In [34]:
#Create columns to day of week, week of year, and hour
df['day_of_week'] = pd.to_datetime(df['Crash timestamp (US/Central)']).dt.weekday
df['week_of_year'] = pd.to_datetime(df['Crash timestamp (US/Central)']).dt.isocalendar().week
df['hour_of_day'] = pd.to_datetime(df['Crash timestamp (US/Central)']).dt.hour

df['units_involved'] = df['units_involved'].str.lower()
for cat in unit_cats:
    df[f'{cat}_involved'] = df['units_involved'].str.contains(cat)

In [35]:
#Drop units_involved column now that this information is replaced by the created flag columns
df.drop(columns=['units_involved'],inplace=True)
df.dropna(inplace=True)

In [36]:
df.head()

,ID,Crash ID,crash_fatal_fl,case_id,rpt_block_num,rpt_street_name,rpt_street_sfx,crash_speed_limit,road_constr_zone_fl,latitude,longitude,crash_sev_id,death_cnt,point,onsys_fl,private_dr_fl,Crash timestamp (US/Central),Estimated Total Comprehensive Cost,Location group,Address,day_of_week,week_of_year,hour_of_day,micromobility device_involved,train_involved,e-scooter_involved,pedestrian_involved,motorcycle_involved,large passenger vehicle_involved,bicycle_involved,passenger car_involved,motor vehicle – other_involved
44014,92807,16839445.0,False,190080930,1200,MOPAC,EXPY,65.0,False,30.288379,-97.762235,5,0,POINT (-97.76223487 30.28837926),True,False,2019-01-09 14:12:00,20000,2.0,1200 N LOOP 1,2,2,14,False,False,False,False,False,True,False,True,False
44015,93467,16854755.0,False,190151441,1700,OHLEN,RD,35.0,False,30.363175,-97.717782,5,0,POINT (-97.71778247 30.36317476),True,False,2019-01-15 20:58:00,40000,1.0,W OHLEN RD & N US 183 SVRD,1,3,20,False,False,False,False,False,False,False,True,False
44018,93480,16854819.0,False,190160293,3100,IH 35,HWY,60.0,False,30.234100,-97.740976,5,0,POINT (-97.7409757 30.23410002),True,False,2019-01-16 07:28:00,40000,2.0,3100 S IH 35,2,3,7,False,False,False,False,False,True,False,False,False
44021,94289,16870096.0,False,190260764,300,E PARMER,LN,50.0,False,30.405288,-97.663709,3,0,POINT (-97.6637086677118 30.405287627981),False,False,2019-01-26 13:41:00,460000,1.0,E PARMER LN & MC CALLEN PASS,5,4,13,False,False,False,False,False,True,False,False,False
44022,93948,16863200.0,False,190230902,8900,GALEWOOD,DR,25.0,False,30.366156,-97.715854,2,0,POINT (-97.71585363 30.3661555),False,False,2019-01-23 13:25:00,540000,1.0,8900 GALEWOOD DR,2,4,13,False,False,False,False,False,True,False,True,False

In [37]:
#Save dataframe as csv
df.to_csv('atx_crash_data_2018-2026_clean.csv', index=False)